### ISSUE TITLE
Easier installation

### ISSUE THREAD

**Issue by dreua** [001101/humhub-module-onlineusers#1]
Can we have this as plugin so that anyone can easily install it through "modules" section of the HumHub admin interface?

**Comment by 001101** [comment]
you can write the HumHub team to integrate it into marketplace, I did this when i wrote it years ago, but seems still did not happened

**Comment by dreua** [comment]
Thanks I didn't know this was a manual process. However, for the use case I was looking into, Mattermost is probably the way to go and it comes with online status by default. Thanks anyway!

**Comment by 001101** [comment]
Just because they both Open Source software, there is no way to even think about comparing them.

**Comment by dreua** [comment]
What exactly do you mean? I'm aware that HumHub and Mattermost are very different in many aspects but I realized that Mattermost is actually what I wanted and HumHub would have been too big in the first place.

Background: Someone was looking for an alternative to Discord and my first idea was HumHub + Jitsi but then I realized that Mattermost + Jitsi comes much closer. This is all really early brainstorming by the way. (HumHub without your plugin would be blocker because seeing someone's online status is a necessary feature to enable Discord-like communication.)

**Comment by 001101** [comment]
I really don't care about your requirements, please don't spam on Github issues
