### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by RoundAboutWEB** [001101/humhub-module-onlineusers#2]
HumHub version: 1.13.2
PHP: 8.2

When calling the configuration page in the module administration, the error situation occurs:
"Oooops ... You might have taken the wrong path. An internal error has occurred."

**Comment by nicochto** [comment]
Same here, running HumHub 1.14.3 with PHP 8.1.
The following error appears in Administration > Information > Logging:
"Error: Class "humhub\compat\CActiveForm" not found in […]/protected/modules/onlineusers/views/config/config.php:14"

**Comment by 001101** [comment]
thanks for the notification, I am currently not active in HumHub development, but have researched that the CActiveForm has been renamed, if someone wants to fix it just proceed like this patch for another module:

issue - https://github.com/StevenJoynt/HumHub-RSS-Reader/issues/21

patch - https://github.com/StevenJoynt/HumHub-RSS-Reader/commit/ec2f6c09b0144344cd22159896df87cf7f95b86a

will see when I can patch it

**Comment by RoundAboutWEB** [comment]
"ArchBlood" has created a bugfix. Can you please release it so that we can use the module - thank you.
https://github.com/001101/humhub-module-onlineusers/pull/3
