### ISSUE TITLE
Move to `humhub` org

### ISSUE THREAD

**Issue by luke-** [001101/humhub-module-onlineusers#4]
Hi PCM,

thank you for this module.

We would like to include this module as an official community module in the Marketplace, move it in the GitHub HumHub organization (as a fork) and develop & maintain it further there. Of course, you will still be listed as an author.

Would that be interesting for you or would you like to continue developing the module in your personal GitHub repo?

I look forward to hearing from you!

Best wishes

Lucas

**Comment by 001101** [comment]
Hello Lucas,

sure we can do it, I am not very active 😄.

Best wishes Paul

**Comment by luke-** [comment]
Hi Paul,

we recently published https://github.com/humhub/online-users

I am currently not sure whether it is based on your module. If so, we can add you as an author of course.

Best wishes

Lucas

**Comment by 001101** [comment]
Thanks, would be nice :)

**Comment by luke-** [comment]
@001101 I'll care about this! Thanks!
